import type { LucideIcon } from 'lucide-react'
import {
  AlignCenter,
  AlignHorizontalSpaceAround,
  AlignLeft,
  AlignRight,
  AlignVerticalSpaceAround,
  Archive,
  ArrowLeft,
  Bookmark,
  Check,
  ChevronDown,
  ChevronUp,
  Code,
  Contrast,
  Copy,
  Cpu,
  Crop,
  Download,
  Droplet,
  Eye,
  EyeOff,
  File,
  FileDiff,
  FilePlus,
  GitMerge,
  Grid2X2,
  Hand,
  Hash,
  Highlighter,
  Image,
  Languages,
  Lock,
  Minimize2,
  Moon,
  Pen,
  Pencil,
  Plus,
  Redo2,
  RotateCw,
  ScanLine,
  Shapes,
  ShieldCheck,
  Sparkles,
  Split,
  Strikethrough,
  Sun,
  Tag,
  Trash2,
  TriangleAlert,
  Type,
  Underline,
  Undo2,
  Unlock,
  WifiOff,
  Workflow,
  Wrench,
  X,
} from 'lucide-react'

const ICONS = {
  merge: GitMerge,
  split: Split,
  filePlus: FilePlus,
  copy: Copy,
  compress: Minimize2,
  rotate: RotateCw,
  image: Image,
  languages: Languages,
  file: File,
  lock: Lock,
  unlock: Unlock,
  droplet: Droplet,
  hash: Hash,
  grid: Grid2X2,
  crop: Crop,
  wrench: Wrench,
  text: Type,
  highlight: Highlighter,
  underline: Underline,
  strikethrough: Strikethrough,
  pen: Pen,
  edit: Pencil,
  shapes: Shapes,
  alignLeft: AlignLeft,
  alignCenter: AlignCenter,
  alignRight: AlignRight,
  alignHorizontal: AlignHorizontalSpaceAround,
  alignVertical: AlignVerticalSpaceAround,
  hand: Hand,
  eyeOff: EyeOff,
  diff: FileDiff,
  code: Code,
  contrast: Contrast,
  archive: Archive,
  bookmark: Bookmark,
  scan: ScanLine,
  shield: ShieldCheck,
  wifiOff: WifiOff,
  cpu: Cpu,
  download: Download,
  trash: Trash2,
  arrowLeft: ArrowLeft,
  undo: Undo2,
  redo: Redo2,
  up: ChevronUp,
  down: ChevronDown,
  sun: Sun,
  moon: Moon,
  check: Check,
  plus: Plus,
  x: X,
  eye: Eye,
  alert: TriangleAlert,
  spark: Sparkles,
  workflow: Workflow,
  tag: Tag,
} as const satisfies Record<string, LucideIcon>

export type IconName = keyof typeof ICONS

type Props = {
  name: IconName
  className?: string
  strokeWidth?: number
}

export function Icon({ name, className = 'size-5', strokeWidth = 1.6 }: Props) {
  const IconComponent = ICONS[name]

  return <IconComponent className={className} strokeWidth={strokeWidth} aria-hidden="true" />
}
