import type { es } from './es'

/** El tipo lo impone el español: si falta una clave, esto no compila. */
export const en: typeof es = {
  meta: {
    lang: 'en',
    homeTitle: '{app} · {tagline}',
    toolTitle: '{tool} · {app}',
    description:
      'PDF tools that run entirely inside your browser. Your documents are never uploaded to any server.',
  },

  brand: {
    tagline: 'Your PDFs, on the sofa. Never leaving your home.',
    claim: [
      'PDF tools that stay ',
      { bold: 'in your browser tab' },
      '. They don’t upload, they don’t travel, they don’t queue at someone else’s server.',
    ],
  },

  header: {
    home: '{app}, home',
    badge: 'Runs on your device',
    howItWorks: 'How it works',
    tools: 'Tools',
  },

  toolGuide: {
    intro:
      '{tool} processes your files directly in the browser. The document is not uploaded to a server and the result is generated locally on your device.',
    howTitle: 'How to use this tool',
    select: 'Select the files you want to process with {tool}.',
    configure: 'Configure the available options.',
    run: 'Click “{action}”.',
    download: 'Download the result when processing is complete.',
    faqTitle: 'Frequently asked questions (FAQ)',
    freeQuestion: 'Is it free?',
    freeAnswer: 'Yes. You can use the tool without creating an account.',
    uploadQuestion: 'Are my files uploaded?',
    uploadAnswer:
      'No. Your files stay in this tab’s memory and are not sent to any server.',
    offlineQuestion: 'Does it work offline?',
    offlineAnswer:
      'Yes, after the application and its required resources have loaded. You can disconnect from the internet and process files already open in the tab.',
    technicalQuestion: 'How does {tool} work?',
  },

  kofi: 'Buy me a coffee',

  footer: {
    line: '© {year} {name}. No file servers, no accounts, no individual tracking.',
    link: 'How to check that we upload nothing',
    contact: 'Contact me or report a problem',
  },

  locale: {
    label: 'Language',
    names: { es: 'Spanish', en: 'English' },
    switchTo: 'Switch to {name}',
  },

  theme: {
    label: 'Theme',
    options: { light: 'Light', dark: 'Dark' },
    toLight: 'Switch to light theme',
    toDark: 'Switch to dark theme',
  },

  hero: {
    badge: 'Your documents never leave your device',
    tools: 'See the tools',
    verify: 'Check it yourself',
  },

  privacyPoints: {
    noUpload: {
      title: 'No uploads',
      body: 'There is no file server. The document is opened with the browser File API and lives only in this tab’s memory.',
    },
    offline: {
      title: 'Works offline',
      body: 'Cut the WiFi and it keeps working. That is the simplest proof that the processing is local.',
    },
    noTracking: {
      title: 'No accounts, no individual tracking',
      body: 'No sign-up, session cookies, advertising or individual tracking. We use Cloudflare Web Analytics to measure performance in aggregate, not to sell you anything.',
    },
    private: {
      title: '100% private',
      body: 'The document is not copied to any disk or server: it only lives in this tab’s memory until you close it.',
    },
  },

  categories: {
    paginas: {
      name: 'Organise pages',
      short: 'Organise',
      blurb: 'Reorder, insert, remove and adjust PDF pages.',
    },
    edicion: {
      name: 'Edit and annotate',
      short: 'Edit',
      blurb: 'Add content, annotations and signatures to the PDF.',
    },
    conversiones: {
      name: 'Convert and extract',
      short: 'Convert',
      blurb: 'Switch formats or extract content from the document.',
    },
    optimizacion: {
      name: 'Optimise and repair',
      short: 'Optimise',
      blurb: 'Reduce, flatten, transform or repair the PDF.',
    },
    metadatos: {
      name: 'Document information',
      short: 'Information',
      blurb: 'Compare, inspect and edit PDF information.',
    },
    seguridad: {
      name: 'Security and privacy',
      short: 'Security',
      blurb: 'Passwords and sensitive content.',
    },
  },

  tabs: {
    all: 'All',
  },

  workflow: {
    badge: 'Workflows',
    badgeBody: 'Apply several actions in sequence to one PDF.',
    title: 'Create a workflow',
    description: 'Choose a PDF and chain actions. Each step receives the PDF generated by the previous one.',
    inputTitle: 'Input document',
    stepsTitle: 'Steps',
    addStep: 'Add action',
    chooseStep: 'Choose an action',
    moveUp: 'Move step up',
    moveDown: 'Move step down',
    remove: 'Remove step',
    run: 'Run workflow',
    running: 'Running step {current} of {total}…',
    empty: 'Add at least one action.',
    noSteps: 'There are no actions yet. Add the first one to begin.',
    limitationTitle: 'Which actions can be chained',
    limitationBody: 'Workflows use PDF→PDF actions that produce one document. Merge, split, compare, and exports to images or text are excluded because they create multiple results, need multiple documents, or change format.',
    done: 'Workflow complete',
    output: 'Final result',
    reset: 'Start over',
    invalidOutput: 'This action does not return one PDF and cannot be used in this workflow.',
    protectLast: 'Protect with password must be the last workflow step.',
    unlockFirst: 'Remove password must be the first workflow step.',
  },

  accept: {
    pdf: 'PDF',
    image: 'JPG or PNG',
    html: 'HTML',
  },

  dropzone: {
    dragOne: 'Drop your {accept} file here',
    dragMany: 'Drop your {accept} files here',
    pickOne: 'Choose file',
    pickMany: 'Choose files',
    hint: 'The file is opened in memory. It is not sent anywhere.',
    up: 'Move up',
    down: 'Move down',
    remove: 'Remove {name}',
  },

  options: {
    title: 'Options',
    on: 'On',
    off: 'Off',
  },

  run: {
    back: 'All tools',
    processing: 'Working…',
    reset: 'Start over',
    needOne: 'Add a file to begin.',
    needMany: 'Add at least {n} files.',
    working: 'Working in your browser…',
    failed: 'Something went wrong while processing the file.',
    doneOne: 'Done, 1 file',
    doneMany: 'Done, {n} files',
    zip: 'Download all (.zip)',
    download: 'Download',
    preview: 'Preview',
    textPreview: 'Report preview',
    close: 'Close',
    loading: 'Loading…',
    ephemeral: 'The results live in this tab’s memory. Closing it discards them.',
    support: {
      title: 'How much is this tool worth to you?',
      body: 'If it has been useful, you can help keep it running with a donation.',
      donate: 'Make a donation',
      later: 'Maybe another time',
    },
  },

  card: {
    soon: 'Soon',
  },

  notFound: {
    kicker: 'Nothing here',
    title: 'This tool does not exist yet',
    body: 'It may be on the way, or the link may be misspelled.',
    cta: 'Back to the start',
  },

  privacy: {
    title: 'How it works, and how to check it',
    intro:
      'Most online PDF tools upload your document to a server, process it there and promise to delete it a few hours later. {app} has no server to upload anything to.',
    steps: {
      pick: {
        title: '1. You pick a file',
        body: 'The browser asks your permission and hands the contents to the tab through the File API. Those contents live in the tab’s RAM; they are not copied to any disk or any server.',
      },
      process: {
        title: '2. It is processed here',
        body: 'The libraries that manipulate the PDF were downloaded with the page and run on your CPU. The heavy work happens in a Web Worker so the interface stays responsive.',
      },
      download: {
        title: '3. You download the result',
        body: 'The output file is built in memory and offered to you as a local download. Close the tab and all of the above is gone.',
      },
    },
    verifyTitle: 'Don’t trust us: verify it',
    verifyBody:
      'Any website can write “we don’t keep your files”. These three checks take you a minute.',
    checks: {
      offline: {
        title: 'Disconnect from the internet',
        body: 'Load the page, turn on airplane mode or switch off the WiFi, then use any tool. If it works with no network, there is nothing on the other side.',
      },
      devtools: {
        title: 'Watch the Network tab in DevTools',
        body: 'Open the developer tools (F12), go to Network and process a document. A Cloudflare Web Analytics request with technical metrics may appear, but there is no POST carrying your file or data derived from it.',
      },
      source: {
        title: 'Read the code',
        body: 'This is a static app: HTML, CSS and JavaScript. You can read the served source and confirm that no upload endpoint exists.',
      },
    },
    limitsTitle: 'What does happen',
    limitsIntro: 'Being honest about the limits is part of the deal:',
    limits: {
      ip: {
        strong: 'Serving the site leaves a trace.',
        body: 'When the page loads, the server that hosts it sees your IP and your browser, like any other website. Cloudflare Web Analytics receives only technical performance metrics and does not use cookies, local storage or fingerprints to follow you. What it never sees is your document.',
      },
      theme: {
        strong: 'Some settings are stored.',
        body: 'Your browser may remember the theme, language and whether you postponed the donation prompt. None of this contains documents or data derived from them.',
      },
      order: {
        strong: 'Which tools you use is remembered.',
        body: 'The browser keeps an anonymous counter of how many times you have finished each tool, so the dashboard can reorder the list to put the ones you use most first. It does not contain documents, file names or anything that could be tied back to you outside this tab.',
      },
      power: {
        strong: 'Your machine does the work.',
        body: 'A very large document may be slow or exhaust the tab’s memory. That is the price of not handing the job to someone else’s server.',
      },
    },
    analytics: {
      title: 'Ethical analytics, nothing to sell you',
      body: 'We will use Cloudflare Web Analytics to understand which pages work and find performance problems. It does not create profiles, use cookies, or track people across visits or sites. It only collects technical page-load metrics; it never receives your documents or data derived from them.',
      link: 'Learn more about Cloudflare Web Analytics privacy',
    },
  },

  errors: {
    badRange: 'I don’t understand "{part}". Use formats like 1-3, 5 or 9-.',
    reversedRange: 'Reversed range in "{part}".',
    emptySelection: 'The page selection is empty.',
    invalidMaxSize: 'The limit must be a number between 0.1 and 500 MB.',
    pageTooLarge: 'Page {page} is {size} MB and exceeds the {max} MB limit.',
    noPage: 'Page {page} does not exist.',
    noPageOf: 'Page {page} does not exist: the document has {total}.',
    invalidCopies: 'The number of copies must be an integer between 2 and 100.',
    exportPage: 'Page {page} could not be exported.',
    noImages: 'No image could be read.',
    emptyPassword: 'Enter a password.',
    passwordMismatch: 'The two passwords do not match.',
    passwordReservedChar: 'The password cannot start with “-” or “@”.',
    passwordTooLong:
      'The password takes {bytes} bytes and the encryption allows {max} (accents and emoji take several).',
    alreadyEncrypted: 'This PDF is already encrypted: remove the current password first.',
    notEncrypted: 'This PDF is not encrypted: there is no password to remove.',
    wrongPassword: 'The password does not open this document.',
    encryptFailed: 'The document could not be encrypted.',
    repairFailed: 'Could not repair it: the damage is beyond what can be rebuilt.',
    signatureEmpty: 'Create a signature before signing the document.',
    repairEncrypted:
      'The document is encrypted: remove the password with Unlock PDF and try again.',
    organizeEmpty: 'No pages left: add at least one before exporting.',
    cropEmpty: 'The crop leaves the page empty: ease one of the margins.',
    redactEmpty: 'Draw at least one rectangle over the text you want to redact.',
    redactFailed: 'Could not render the page for redaction.',
    ocrFailed: 'Could not recognise the text on page {n}.',
    compareNeedTwo: 'Upload two PDFs to compare.',
    compareFailed: 'Could not compare the pages.',
    blankPagesAll: 'The document contains only blank pages.',
    blankPagesFailed: 'The blank pages could not be detected.',
    flattenFailed: 'The form fields could not be flattened.',
    editEmpty: 'Add at least one element before exporting.',
    bookmarksEmpty: 'Add at least one bookmark before exporting.',
    bookmarkTitle: 'Every bookmark needs a title.',
    bookmarkPage: 'Page {page} does not exist: the document has {total}.',
    headerFooterEmpty: 'Enter text for the header or footer.',
  },

  filenames: {
    merged: 'merged',
    images: 'images',
    extractedImages: 'extracted-images',
    selection: 'selection',
    sizePart: 'part',
    numbered: 'numbered',
    compressed: 'compressed',
    grayscale: 'grayscale',
    flattened: 'flattened',
    rotated: 'rotated',
    inserted: 'inserted',
    duplicated: 'duplicated',
    repaired: 'repaired',
    protected: 'protected',
    unlocked: 'unlocked',
    watermark: 'watermark',
    signed: 'signed',
    organized: 'organised',
    nUp: 'n-up',
    blankPagesRemoved: 'without-blank-pages',
    cropped: 'cropped',
    redacted: 'redacted',
    ocr: 'ocr',
    compared: 'compared',
    edited: 'edited',
    metadata: 'metadata',
    report: 'technical-report',
    accessibility: 'accessibility',
    bookmarks: 'bookmarks',
    headerFooter: 'header-footer',
  },

  progress: {
    page: 'Page {n}',
    document: 'Document {n} of {total}',
    reading: 'Reading {name}',
    readingPdf: 'Reading the PDF',
    compressingImages: 'Compressing images',
    grayscalingImages: 'Converting images to grayscale',
    extractingImages: 'Extracting images',
    writingPdf: 'Writing the PDF',
    repairing: 'Rebuilding the structure',
    rebuildingObjects: 'Recovering the objects',
    salvaging: 'Salvaging what is left',
    encrypting: 'Encrypting the document',
    decrypting: 'Decrypting the document',
    flattening: 'Flattening the form fields',
    removingBlankPages: 'Removing blank pages',
    sheet: 'Composing sheet {n} of {total}',
    done: 'Done',
  },

  report: {
    title: 'PDF technical report',
    file: 'File',
    size: 'Size',
    pages: 'Pages',
    page: 'Page',
    dimensions: 'Page size',
    fonts: 'Detected fonts',
    images: 'Detected images',
    forms: 'Forms',
    fields: 'Form fields',
    encryption: 'Encryption',
    metadata: 'Metadata',
    titleField: 'Title',
    author: 'Author',
    subject: 'Subject',
    keywords: 'Keywords',
    yes: 'Yes',
    no: 'No',
    detected: 'Detected',
    none: 'None detected',
    unavailable: 'Not analyzable',
    unavailableDetails: 'Cannot be analyzed reliably in this document',
    encrypted: 'Yes, the content is encrypted',
    plain: 'No',
    unknown: 'Could not determine',
    embeddingUnknown: 'Whether the fonts are embedded cannot be determined.',
    encryptedContent: 'The document is encrypted; pages, fonts, images and forms cannot be analyzed without the password.',
    pageError: 'This page could not be analyzed.',
    footer: 'Generated locally in the browser. The document and this report were not sent to any server.',
    pageDetails: 'Page details',
  },

  accessibility: {
    title: 'Basic PDF accessibility check',
    file: 'File',
    size: 'Size',
    result: 'Result',
    pass: 'Yes',
    fail: 'No',
    warning: 'Review',
    unknown: 'Cannot determine',
    titleCheck: 'Document title',
    titlePresent: 'A title is present in the metadata.',
    titleMissing: 'There is no title in the metadata.',
    language: 'Document language',
    languagePresent: 'Declared: {value}.',
    languageMissing: 'No language has been declared.',
    tagging: 'Tagged document',
    taggingPresent: 'Marked content and a tagged structure were detected.',
    taggingMissing: 'No marked content or tagged structure was detected.',
    altText: 'Alternative text for figures',
    altSummary: '{withAlt} of {total} figures have alternative text.',
    altMissing: 'Some figures have no alternative text.',
    noFigures: 'No figures were detected in the structure.',
    headings: 'Heading order and structure',
    headingsSummary: 'Headings detected: {value}.',
    headingsMissing: 'No tagged headings were detected.',
    headingsOrder: 'Level jumps detected: {value}.',
    headingsOk: 'Heading levels have no detected jumps.',
    contrast: 'Contrast',
    contrastUnknown: 'It cannot be determined reliably without interpreting each page visually.',
    unavailable: 'Cannot analyze',
    pageError: 'This page could not be analyzed.',
    disclaimer: 'This check is indicative and does not replace a complete accessibility audit. Review the PDF with specialist tools and users of assistive technology.',
    footer: 'Generated locally in the browser. The document and this report were not sent to any server.',
  },

  tools: {
    merge: {
      name: 'Merge PDF',
      short: 'Combine several documents into one, in the order you choose.',
      description:
        'Joins several PDFs into a single document. The list order is the final order; you can rearrange it before processing.',
      action: 'Merge PDF',
    },
    split: {
      name: 'Split PDF',
      short: 'Break it up by ranges, or pull out just the pages you need.',
      description:
        'Splits a PDF into several documents by page ranges, one per page, or extracts a specific selection into a single file.',
      action: 'Split PDF',
      options: {
        mode: {
          label: 'Mode',
          choices: {
            ranges: 'One PDF per range',
            extract: 'Extract the selection into one PDF',
            each: 'One PDF per page',
            size: 'Split by maximum size',
          },
        },
        ranges: {
          label: 'Pages',
          help: 'Comma-separated ranges. Leave "1-" for the whole document.',
        },
        maxSize: { label: 'Maximum size (MB)' },
      },
      note: 'In size mode, page order is preserved. If a page by itself exceeds the limit, a warning is shown and the page is not modified.',
    },
    insert: {
      name: 'Add blank pages',
      short: 'Insert one or more blank pages wherever you need them.',
      description:
        'Adds new pages before or after the pages you choose, using the size and orientation you select.',
      action: 'Add pages',
      options: {
        pages: {
          label: 'Reference pages',
          help: 'Enter one or more pages separated by commas, for example: 2, 5, 8.',
        },
        position: {
          label: 'Insert',
          choices: { before: 'Before each page', after: 'After each page' },
        },
        pageSize: {
          label: 'Page size',
          choices: { a4: 'A4', letter: 'Letter' },
        },
        orientation: {
          label: 'Orientation',
          choices: { portrait: 'Portrait', landscape: 'Landscape' },
        },
      },
    },
    duplicate: {
      name: 'Duplicate pages',
      short: 'Repeat the pages you choose within the same PDF.',
      description:
        'Duplicates a page selection as many times as you specify. The rest of the document keeps its order, size and orientation.',
      action: 'Duplicate pages',
      options: {
        pages: {
          label: 'Pages',
          help: 'Use comma-separated ranges, for example: 1-3, 5, 9-.',
        },
        copies: { label: 'Number of copies' },
      },
    },
    rotate: {
      name: 'Rotate PDF',
      short: 'Turn every page, or only the ones you name.',
      description:
        'Applies a 90, 180 or 270 degree turn. The rotation adds to whatever each page already had.',
      action: 'Rotate PDF',
      options: {
        angle: {
          label: 'Turn',
          choices: {
            '90': '90° clockwise',
            '180': '180°',
            '270': '90° counter-clockwise',
          },
        },
        pages: {
          label: 'Pages',
          help: 'Leave "1-" to rotate the whole document.',
        },
      },
    },
    organize: {
      name: 'Organise pages',
      short: 'Reorder, duplicate and delete pages from one or more PDFs using thumbnails.',
      description:
        'Thumbnail view to reorder, duplicate or delete pages from one or more PDFs before exporting. Documents are concatenated in the order they appear in the list.',
      action: 'Organise',
      note: 'The list order is the final order. Drag to reorder or use the buttons. With several PDFs they are concatenated in the list order.',
      preview: {
        title: 'Pages',
        hint: 'Drag thumbnails to reorder. Each page keeps its source document and original page number on the right.',
        position: 'Position',
        original: 'Original {n}',
        docAndPage: 'Doc {file} · p. {page}',
        moveUp: 'Move up',
        moveDown: 'Move down',
        duplicate: 'Duplicate',
        remove: 'Remove',
        reset: 'Reset order',
        empty: 'No pages left. Duplicate one to get started.',
        count: '{n} pages',
      },
    },
    'n-up': {
      name: 'Multiple pages per sheet',
      short: 'Place 2, 4, 6, or 8 pages on each sheet.',
      description: 'Creates a print-ready PDF with multiple pages per sheet, scaled without distortion and processed entirely in the browser.',
      action: 'Compose sheets',
      options: {
        pagesPerSheet: { label: 'Pages per sheet', choices: { '2': '2 pages', '4': '4 pages', '6': '6 pages', '8': '8 pages' } },
        orientation: { label: 'Orientation', choices: { portrait: 'Portrait', landscape: 'Landscape' } },
        margin: { label: 'Margin (pt)' },
        order: { label: 'Reading order', choices: { rows: 'Rows first', columns: 'Columns first' } },
        lines: { label: 'Separator lines' },
      },
    },
    'remove-blank-pages': {
      name: 'Remove blank pages',
      short: 'Detect and remove visually empty pages from a PDF.',
      description:
        'Analyses every page in the browser and removes pages containing only a white background. All other content stays intact and is not rasterised.',
      action: 'Remove blank pages',
      note: 'Detection is based on visible appearance: marks that are almost white may be treated as blank.',
    },

    'jpg-to-pdf': {
      name: 'Images to PDF',
      short: 'Turn JPG and PNG files into a PDF, one image per page.',
      description:
        'Builds a PDF from images. You can fit them to A4 or Letter with a margin, or let each page take the exact size of its image.',
      action: 'Create PDF',
      options: {
        pageSize: {
          label: 'Page size',
          choices: { a4: 'A4', letter: 'Letter', fit: 'Fit to image' },
        },
        landscape: { label: 'Landscape' },
        margin: { label: 'Margin (pt)' },
      },
    },
    'pdf-to-jpg': {
      name: 'PDF to images',
      short: 'Export the pages as JPG or PNG at the resolution you want.',
      description:
        'Rasterises each page with the same render engine the browser viewer uses and exports it as an image.',
      action: 'Export images',
      note: 'Rasterising turns text into pixels: the result is no longer selectable or searchable.',
      options: {
        pages: { label: 'Pages' },
        format: {
          label: 'Format',
          choices: { jpeg: 'JPG', png: 'PNG (lossless)' },
        },
        scale: {
          label: 'Resolution',
          choices: {
            '1': '72 dpi (screen)',
            '2': '144 dpi (recommended)',
            '4': '288 dpi (print)',
          },
        },
        quality: { label: 'JPG quality' },
      },
    },
    'extract-images': {
      name: 'Extract images',
      short: 'Take the embedded images out of a PDF as separate files.',
      description:
        'Reads the image objects contained in the PDF and exports them as PNG files, without rasterising pages or changing text.',
      action: 'Extract images',
      note: 'Images reused on several pages are returned only once. Masks and vector graphics are not treated as embedded images.',
    },
    'pdf-to-text': {
      name: 'PDF to text',
      short: 'Extract the text already present in the document.',
      description: 'Dumps the textual content of the PDF as plain text, without OCR.',
      action: 'Extract text',
      note: 'Only extracts text already embedded in the PDF. For scanned documents, use the OCR tool.',
    },
    ocr: {
      name: 'OCR',
      short: 'Recognise text in scanned documents and make it searchable.',
      description:
        'Runs optical recognition over the scanned pages and adds an invisible text layer so you can search and copy.',
      action: 'Recognise text',
      note: 'The language model is served from the same origin (~2-4 MB per language, cached). The pages never leave the browser.',
      options: {
        language: {
          label: 'Document language',
          choices: { spa: 'Spanish', eng: 'English' },
        },
      },
    },

    number: {
      name: 'Number pages',
      short: 'Add page numbers in the position and format you choose.',
      description:
        'Writes the page number onto the document using one of the PDF base fonts, so it does not grow the file.',
      action: 'Number pages',
      options: {
        position: {
          label: 'Position',
          choices: {
            'bottom-center': 'Bottom centre',
            'bottom-right': 'Bottom right',
            'bottom-left': 'Bottom left',
            'top-center': 'Top centre',
            'top-right': 'Top right',
            'top-left': 'Top left',
          },
        },
        start: { label: 'Start at' },
        size: { label: 'Size (pt)' },
        margin: { label: 'Margin (pt)' },
        withTotal: { label: 'Show "n / total"' },
        skipFirst: { label: 'Skip the cover page' },
      },
    },
    'header-footer': {
      name: 'Header and footer',
      short: 'Add configurable text above or below the pages.',
      description:
        'Write a header, a footer or both. You can insert the page number, total, file name and local date.',
      action: 'Add header and footer',
      options: {
        header: {
          label: 'Header',
          help: 'Variables: {page}, {total}, {file}, {date}. It may be left empty.',
        },
        footer: {
          label: 'Footer',
          help: 'Variables: {page}, {total}, {file}, {date}. It may be left empty.',
        },
        size: { label: 'Size (pt)' },
        margin: { label: 'Margin (pt)' },
        pages: { label: 'Pages', help: 'Leave "1-" to apply it to the whole document.' },
      },
    },
    watermark: {
      name: 'Watermark',
      short: 'Overlay text or a logo on every page.',
      description: 'Adds a watermark with control over opacity, rotation and position.',
      action: 'Apply watermark',
      options: {
        text: { label: 'Text' },
        position: {
          label: 'Position',
          choices: {
            center: 'Centre (diagonal)',
            'top-left': 'Top left',
            'top-center': 'Top centre',
            'top-right': 'Top right',
            'bottom-left': 'Bottom left',
            'bottom-center': 'Bottom centre',
            'bottom-right': 'Bottom right',
          },
        },
        color: {
          label: 'Color',
          choices: { gray: 'Grey', red: 'Red', blue: 'Blue', black: 'Black' },
        },
        opacity: { label: 'Opacity (%)' },
        size: { label: 'Size (pt)' },
        rotation: { label: 'Rotation (°)' },
        pages: {
          label: 'Pages',
          help: 'Leave "1-" to mark the whole document.',
        },
      },
    },
    crop: {
      name: 'Crop',
      short: 'Adjust the visible margins of the pages.',
      description: 'Changes the visible area of the document without touching its content.',
      action: 'Crop',
      note: 'Cropping only changes the visible box: anything outside it is still in the file, just not shown.',
      options: {
        applyTo: {
          label: 'Apply to',
          choices: { all: 'All pages', one: 'This page only' },
        },
      },
      preview: {
        title: 'Visible area',
        hint: 'Click and drag on the page to create the crop. Then move it or resize it from the corners.',
        reset: 'Reset',
        newCrop: 'New crop',
        pageOf: 'Page {n} of {total}',
        prevPage: 'Previous page',
        nextPage: 'Next page',
      },
    },
    compare: {
      name: 'Compare PDF',
      short: 'Put two versions side by side and highlight what changed.',
      description: 'Compares two PDFs page by page: red on A = what was removed, green on B = what was added.',
      action: 'Compare',
      note: 'Pages are paired by index. If one PDF is longer, the extra pages are added unchanged.',
      options: {
        tolerance: {
          label: 'Difference tolerance',
          help: 'From 0 (any change) to 255 (only very large differences). 30 is a reasonable default for most documents.',
        },
      },
    },

    compress: {
      name: 'Compress PDF',
      short: 'Shrink the PDF without uploading it to any server.',
      description:
        'Compresses the embedded images and cleans up the internal structure of the document. Text stays text: it is left untouched.',
      action: 'Compress PDF',
      options: {
        level: {
          label: 'Level',
          choices: {
            light: 'Light (less reduction)',
            balanced: 'Balanced',
            max: 'Maximum (more reduction)',
          },
        },
      },
      guide: {
        intro:
          'Compress PDF files directly in your browser without uploading them to a server. {app} processes your files locally on your device.',
        howTitle: 'How to compress a PDF',
        steps: [
          'Select your PDF.',
          'Choose the compression level.',
          'Compress your file.',
          'Download the result.',
        ],
        faqTitle: 'Frequently asked questions about PDF compression (FAQ)',
        faq: [
          {
            question: 'Is {app} really free?',
            answer: 'Yes. The tool is free and you do not need to create an account.',
          },
          {
            question: 'Are my files uploaded?',
            answer:
              'No. The PDF is opened and processed in your browser memory; the document and its derived data do not travel to any server.',
          },
          {
            question: 'Does it work offline?',
            answer:
              'Yes, once the application and its required resources have loaded. You can disconnect from the internet after opening the tool and still process your PDF.',
          },
          {
            question: 'What compression does {app} use?',
            answer:
              'It rewrites the PDF with pdf-lib and re-encodes embedded JPEG images through the browser canvas. The selected level changes their scale and quality; text remains text and is not rasterised. PNG, CMYK and masked images are not modified for now.',
          },
        ],
      },
    },
    grayscale: {
      name: 'Grayscale PDF',
      short: 'Convert a PDF to black and white for printing or a smaller file.',
      description:
        'Converts text and graphics colours to luminance and re-encodes JPEG images as grayscale. Text remains text and is not rasterised.',
      action: 'Convert to grayscale',
      note: 'Transparency, colour profiles, and image formats other than JPEG may retain some of their original behaviour or colour.',
    },
    flatten: {
      name: 'Flatten PDF',
      short: 'Turn fillable fields into fixed page content.',
      description:
        'Integrates the visible form values into the pages and removes their editable fields, without rasterising text or graphics.',
      action: 'Flatten PDF',
      note: 'Flattens AcroForm fields. They cannot be edited or filled in afterwards.',
    },
    repair: {
      name: 'Repair PDF',
      short: 'Recover documents with a damaged structure.',
      description: 'Rewrites the PDF cross-reference table to rescue files that will not open.',
      action: 'Repair',
      note: 'It tries several strategies, from the most faithful to the most aggressive. What was lost does not come back: from a truncated file it salvages up to the last complete object.',
    },

    protect: {
      name: 'Password-protect',
      short: 'Encrypt the document with AES on your own machine.',
      description:
        'Encrypts the PDF with AES-256 and a password. The password is never transmitted because there is nothing to transmit it to.',
      action: 'Protect',
      options: {
        password: { label: 'Password' },
        confirm: { label: 'Repeat the password' },
      },
    },
    unlock: {
      name: 'Remove password',
      short: 'Strip the encryption from a PDF whose password you know.',
      description: 'Decrypts the document and saves an unprotected copy.',
      action: 'Remove password',
      note: 'The password is required. This does not break someone else’s encryption.',
      options: {
        password: {
          label: 'Password',
          help: 'If the document opens without asking for one, leave it empty.',
        },
      },
    },
    sign: {
      name: 'Sign PDF',
      short: 'Place your signature on the document.',
      description: 'Type, draw or upload your signature and place it anywhere with a page preview.',
      action: 'Sign',
      note: 'The signature is visual: it is stamped as an image. It does not produce a cryptographic signature.',
      options: {
        applyTo: {
          label: 'Apply to',
          choices: { one: 'This page only', all: 'All pages' },
        },
      },
      preview: {
        source: 'Signature source',
        modes: { text: 'Text', draw: 'Draw', image: 'Image' },
        textPlaceholder: 'Your name',
        textHint: 'Re-renders on every change with the chosen style.',
        textStyle: 'Style',
        textColor: 'Color',
        textSize: 'Size',
        styles: { script: 'Script', serif: 'Serif', sans: 'Sans' },
        colors: { black: 'Black', blue: 'Blue', gray: 'Grey' },
        drawHint: 'Draw with the mouse or your finger.',
        drawClear: 'Clear',
        imageHint: 'Upload an image. PNG with a transparent background works best.',
        imageChange: 'Change image',
        noImage: 'You have not uploaded an image yet.',
        position: 'Position',
        positionHint: 'Click or drag on the page to place the signature.',
        widthLabel: 'Width on the page (pt)',
        pageOf: 'Page {n} of {total}',
        prevPage: 'Previous page',
        nextPage: 'Next page',
        empty: 'Create or upload a signature to see the preview.',
      },
    },
    edit: {
      name: 'Edit PDF',
      short: 'Add text, images, drawings and shapes to your pages.',
      description: 'Visually edit a PDF in your browser with text, image, pencil and shape tools.',
      action: 'Export edited PDF',
      note: 'Elements are placed as new content over the page. The original PDF text is not modified.',
      preview: {
        title: 'PDF editor', hint: 'Choose a tool and draw on the page. Use the hand to select and move elements.',
        hand: 'Select and move', organizeLabel: 'Arrange', bringForward: 'Bring forward', sendBackward: 'Send backward', alignHorizontal: 'Center horizontally', alignVertical: 'Center vertically', text: 'Add text', image: 'Add image', pencil: 'Draw with pencil', shape: 'Add shape', highlight: 'Highlight text', underlineText: 'Underline text', strikeText: 'Strike through text',
        color: 'Text / stroke', borderColor: 'Border color', strokeWidth: 'Width', alignment: 'Alignment', background: 'Background', transparent: 'Transparent', opacity: 'Opacity', style: 'Style', content: 'Text', font: 'Font', size: 'Size',
        rectangle: 'Rectangle', ellipse: 'Ellipse', triangle: 'Triangle', alignLeft: 'Left', alignCenter: 'Center', alignRight: 'Right',
        delete: 'Delete', rotate: 'Rotate', resize: 'Resize', undo: 'Undo', redo: 'Redo', pageNumber: 'Page number', boldMark: 'B', italicMark: 'I', underlineMark: 'U', defaultText: 'Write here', pageOf: 'Page {n} of {total}', prevPage: 'Previous page', nextPage: 'Next page',
      },
    },
    redact: {
      name: 'Redact',
      short: 'Remove text from the PDF irreversibly.',
      description: 'Draw rectangles over the text you want gone. The text is deleted from the document, not covered with a box.',
      action: 'Redact',
      note: 'The selected text is removed from the PDF: the whole page becomes an image and the text stops being text. This is not reversible.',
      preview: {
        title: 'Areas to redact',
        hint: 'Drag on the page to draw a rectangle. Click an existing one to delete it.',
        clearPage: 'Clear page',
        removeRegion: 'Remove this rectangle',
        pageOf: 'Page {n} of {total}',
        prevPage: 'Previous page',
        nextPage: 'Next page',
      },
    },
    metadata: {
      name: 'Edit metadata',
      short: 'Change the PDF title, author, subject and keywords.',
      description:
        'Edit the PDF information dictionary fields (Title, Author, Subject, Keywords). They are pre-filled with the document’s current values on load.',
      action: 'Apply metadata',
      note: 'To share the file without leaving a trail, leave every field blank. The modification date is updated by the library itself on save.',
      options: {
        title: { label: 'Title' },
        author: { label: 'Author' },
        subject: { label: 'Subject' },
        keywords: {
          label: 'Keywords',
          placeholder: 'report, 2026, invoicing',
        },
      },
      preview: {
        statusLoading: 'Reading the PDF metadata…',
        statusLoaded: 'Current PDF values loaded.',
        statusEmpty: 'The PDF has no metadata.',
        statusError: 'Could not read the metadata.',
        clearAll: 'Clear all fields',
      },
    },
    report: {
      name: 'PDF technical report',
      short: 'Inspect and download a technical summary of the document.',
      description: 'Analyze the visible PDF structure locally and generate a downloadable technical report.',
      action: 'Generate report',
      note: 'The report distinguishes detected data from aspects PDF.js cannot analyze reliably.',
    },
    accessibility: {
      name: 'Check PDF accessibility',
      short: 'Detects basic accessibility issues in the document structure.',
      description: 'Analyzes the title, language, tagging, alternative text and headings of a PDF locally, then generates an understandable report.',
      action: 'Check accessibility',
      note: 'This is an indicative check: it does not replace a complete accessibility audit or testing with assistive technologies.',
    },
    bookmarks: {
      name: 'Create bookmarks',
      short: 'Add hierarchical navigation to your PDF.',
      description: 'Create PDF bookmarks with titles, destination pages and nested levels.',
      action: 'Create bookmarks',
      note: 'Existing bookmarks are replaced by the ones you define here and will appear in the PDF viewer. No page is changed or added to the document.',
      preview: {
        title: 'PDF bookmarks',
        hint: 'Add one entry per row. Level 1 is a top-level entry; higher levels are nested under the previous compatible entry.',
        entryTitle: 'Title',
        entryTitlePlaceholder: 'For example, Introduction',
        page: 'Page',
        level: 'Level',
        add: 'Add bookmark',
        remove: 'Remove bookmark {n}',
      },
    },
  },
}
