import type { Tool, ToolCategoryId } from './types'
import { getToolUsage } from '@/lib/usage'
import { CropPreview } from './CropPreview'
import { OrganizePreview } from './OrganizePreview'
import { RedactPreview } from './RedactPreview'
import { SignaturePreview } from './SignaturePreview'
import { EditPreview } from './EditPreview'
import { MetadataPreview } from './MetadataPreview'

/** Los ids son estables: se usan como ancla en la URL y como clave del diccionario. */
export const CATEGORY_IDS: ToolCategoryId[] = [
  'paginas',
  'edicion',
  'conversiones',
  'seguridad',
]

const PDF = { accept: 'application/pdf,.pdf', acceptKey: 'pdf' } as const

export const TOOLS: Tool[] = [
  {
    slug: 'merge',
    icon: 'merge',
    category: 'paginas',
    status: 'ready',
    ...PDF,
    multiple: true,
    minFiles: 2,
    load: () => import('./impl/merge').then((m) => m.run),
  },
  {
    slug: 'split',
    icon: 'split',
    category: 'paginas',
    status: 'ready',
    ...PDF,
    multiple: false,
    minFiles: 1,
    options: [
      { key: 'mode', type: 'select', default: 'ranges', choices: ['ranges', 'extract', 'each', 'size'] },
      {
        key: 'ranges',
        type: 'text',
        default: '1-',
        // Un ejemplo de rangos no se traduce.
        placeholder: '1-3, 5, 9-',
        showIf: (values) => values.mode !== 'each' && values.mode !== 'size',
      },
      {
        key: 'maxSize',
        type: 'number',
        default: 10,
        min: 0.1,
        max: 500,
        step: 0.1,
        showIf: (values) => values.mode === 'size',
      },
    ],
    load: () => import('./impl/split').then((m) => m.run),
  },
  {
    slug: 'insert',
    icon: 'filePlus',
    category: 'edicion',
    status: 'ready',
    ...PDF,
    multiple: false,
    minFiles: 1,
    workflow: true,
    options: [
      { key: 'pages', type: 'text', default: '1', placeholder: '2, 5, 8' },
      { key: 'position', type: 'select', default: 'before', choices: ['before', 'after'] },
      { key: 'pageSize', type: 'select', default: 'a4', choices: ['a4', 'letter'] },
      { key: 'orientation', type: 'select', default: 'portrait', choices: ['portrait', 'landscape'] },
    ],
    load: () => import('./impl/insert').then((m) => m.run),
  },
  {
    slug: 'duplicate',
    icon: 'copy',
    category: 'edicion',
    status: 'ready',
    ...PDF,
    multiple: false,
    minFiles: 1,
    workflow: true,
    options: [
      { key: 'pages', type: 'text', default: '1-', placeholder: '1-3, 5, 9-' },
      { key: 'copies', type: 'number', default: 2, min: 2, max: 100 },
    ],
    load: () => import('./impl/duplicate').then((m) => m.run),
  },
  {
    slug: 'rotate',
    icon: 'rotate',
    category: 'edicion',
    status: 'ready',
    ...PDF,
    multiple: false,
    minFiles: 1,
    workflow: true,
    options: [
      { key: 'angle', type: 'select', default: '90', choices: ['90', '180', '270'] },
      { key: 'pages', type: 'text', default: '1-', placeholder: '1-3, 5' },
    ],
    load: () => import('./impl/rotate').then((m) => m.run),
  },
  {
    slug: 'organize',
    icon: 'grid',
    category: 'paginas',
    status: 'ready',
    ...PDF,
    multiple: true,
    minFiles: 1,
    load: () => import('./impl/organize').then((m) => m.run),
    Preview: OrganizePreview,
  },
  {
    slug: 'n-up',
    icon: 'grid',
    category: 'paginas',
    status: 'ready',
    ...PDF,
    multiple: false,
    minFiles: 1,
    workflow: true,
    options: [
      { key: 'pagesPerSheet', type: 'select', default: '4', choices: ['2', '4', '6', '8'] },
      { key: 'orientation', type: 'select', default: 'portrait', choices: ['portrait', 'landscape'] },
      { key: 'margin', type: 'number', default: 24, min: 0, max: 120, step: 4 },
      { key: 'order', type: 'select', default: 'rows', choices: ['rows', 'columns'] },
      { key: 'lines', type: 'toggle', default: false },
    ],
    load: () => import('./impl/n-up').then((m) => m.run),
  },
  {
    slug: 'remove-blank-pages',
    icon: 'trash',
    category: 'paginas',
    status: 'ready',
    ...PDF,
    multiple: false,
    minFiles: 1,
    workflow: true,
    load: () => import('./impl/remove-blank-pages').then((m) => m.run),
  },
  {
    slug: 'number',
    icon: 'hash',
    category: 'edicion',
    status: 'ready',
    ...PDF,
    multiple: false,
    minFiles: 1,
    workflow: true,
    options: [
      {
        key: 'position',
        type: 'select',
        default: 'bottom-center',
        choices: [
          'bottom-center',
          'bottom-right',
          'bottom-left',
          'top-center',
          'top-right',
          'top-left',
        ],
      },
      { key: 'start', type: 'number', default: 1, min: 0, max: 9999 },
      { key: 'size', type: 'number', default: 10, min: 6, max: 48 },
      { key: 'margin', type: 'number', default: 28, min: 4, max: 120, step: 4 },
      { key: 'withTotal', type: 'toggle', default: false },
      { key: 'skipFirst', type: 'toggle', default: false },
    ],
    load: () => import('./impl/number').then((m) => m.run),
  },
  {
    slug: 'watermark',
    icon: 'droplet',
    category: 'edicion',
    status: 'ready',
    ...PDF,
    multiple: false,
    minFiles: 1,
    workflow: true,
    options: [
      { key: 'text', type: 'text', default: 'CONFIDENCIAL' },
      {
        key: 'position',
        type: 'select',
        default: 'center',
        choices: [
          'center',
          'top-left',
          'top-center',
          'top-right',
          'bottom-left',
          'bottom-center',
          'bottom-right',
        ],
      },
      { key: 'color', type: 'select', default: 'gray', choices: ['gray', 'red', 'blue', 'black'] },
      { key: 'opacity', type: 'number', default: 20, min: 5, max: 100, step: 5 },
      { key: 'size', type: 'number', default: 72, min: 12, max: 200, step: 4 },
      { key: 'rotation', type: 'number', default: -45, min: -90, max: 90, step: 5 },
      { key: 'pages', type: 'text', default: '1-', placeholder: '1-3, 5' },
    ],
    load: () => import('./impl/watermark').then((m) => m.run),
  },
  {
    slug: 'crop',
    icon: 'crop',
    category: 'edicion',
    status: 'ready',
    ...PDF,
    multiple: false,
    minFiles: 1,
    options: [
      { key: 'applyTo', type: 'select', default: 'all', choices: ['all', 'one'] },
    ],
    load: () => import('./impl/crop').then((m) => m.run),
    Preview: CropPreview,
  },
  {
    slug: 'compare',
    icon: 'diff',
    category: 'paginas',
    status: 'ready',
    ...PDF,
    multiple: true,
    minFiles: 2,
    options: [
      { key: 'tolerance', type: 'number', default: 30, min: 0, max: 255 },
    ],
    load: () => import('./impl/compare').then((m) => m.run),
  },

  {
    slug: 'jpg-to-pdf',
    icon: 'image',
    category: 'conversiones',
    status: 'ready',
    accept: 'image/jpeg,image/png,.jpg,.jpeg,.png',
    acceptKey: 'image',
    multiple: true,
    minFiles: 1,
    options: [
      { key: 'pageSize', type: 'select', default: 'a4', choices: ['a4', 'letter', 'fit'] },
      {
        key: 'landscape',
        type: 'toggle',
        default: false,
        showIf: (values) => values.pageSize !== 'fit',
      },
      {
        key: 'margin',
        type: 'number',
        default: 24,
        min: 0,
        max: 200,
        step: 4,
        showIf: (values) => values.pageSize !== 'fit',
      },
    ],
    load: () => import('./impl/images-to-pdf').then((m) => m.run),
  },
  {
    slug: 'pdf-to-jpg',
    icon: 'file',
    category: 'conversiones',
    status: 'ready',
    ...PDF,
    multiple: false,
    minFiles: 1,
    options: [
      { key: 'pages', type: 'text', default: '1-', placeholder: '1-3, 5' },
      { key: 'format', type: 'select', default: 'jpeg', choices: ['jpeg', 'png'] },
      { key: 'scale', type: 'select', default: '2', choices: ['1', '2', '4'] },
      {
        key: 'quality',
        type: 'number',
        default: 85,
        min: 40,
        max: 100,
        step: 5,
        showIf: (values) => values.format === 'jpeg',
      },
    ],
    load: () => import('./impl/pdf-to-images').then((m) => m.run),
  },
  {
    slug: 'extract-images',
    icon: 'image',
    category: 'conversiones',
    status: 'ready',
    ...PDF,
    multiple: false,
    minFiles: 1,
    load: () => import('./impl/extract-images').then((m) => m.run),
  },
  {
    slug: 'pdf-to-text',
    icon: 'text',
    category: 'conversiones',
    status: 'ready',
    ...PDF,
    multiple: false,
    minFiles: 1,
    load: () => import('./impl/pdf-to-text').then((m) => m.run),
  },
  {
    slug: 'ocr',
    icon: 'scan',
    category: 'conversiones',
    status: 'ready',
    ...PDF,
    multiple: false,
    minFiles: 1,
    workflow: true,
    options: [
      { key: 'language', type: 'select', default: 'spa', choices: ['spa', 'eng'] },
    ],
    load: () => import('./impl/ocr').then((m) => m.run),
  },
  {
    slug: 'compress',
    icon: 'compress',
    category: 'conversiones',
    status: 'ready',
    ...PDF,
    multiple: false,
    minFiles: 1,
    workflow: true,
    options: [
      { key: 'level', type: 'select', default: 'balanced', choices: ['light', 'balanced', 'max'] },
    ],
    load: () => import('./impl/compress').then((m) => m.run),
  },
  {
    slug: 'grayscale',
    icon: 'contrast',
    category: 'conversiones',
    status: 'ready',
    ...PDF,
    multiple: false,
    minFiles: 1,
    workflow: true,
    load: () => import('./impl/grayscale').then((m) => m.run),
  },
  {
    slug: 'flatten',
    icon: 'archive',
    category: 'conversiones',
    status: 'ready',
    ...PDF,
    multiple: false,
    minFiles: 1,
    workflow: true,
    load: () => import('./impl/flatten').then((m) => m.run),
  },
  {
    slug: 'repair',
    icon: 'wrench',
    category: 'conversiones',
    status: 'ready',
    ...PDF,
    multiple: false,
    minFiles: 1,
    workflow: true,
    load: () => import('./impl/repair').then((m) => m.run),
  },
  {
    slug: 'protect',
    icon: 'lock',
    category: 'seguridad',
    status: 'ready',
    ...PDF,
    multiple: false,
    minFiles: 1,
    workflow: true,
    options: [
      { key: 'password', type: 'password', default: '' },
      { key: 'confirm', type: 'password', default: '' },
    ],
    load: () => import('./impl/protect').then((m) => m.run),
  },
  {
    slug: 'unlock',
    icon: 'unlock',
    category: 'seguridad',
    status: 'ready',
    ...PDF,
    multiple: false,
    minFiles: 1,
    workflow: true,
    options: [{ key: 'password', type: 'password', default: '' }],
    load: () => import('./impl/unlock').then((m) => m.run),
  },
  {
    slug: 'sign',
    icon: 'pen',
    category: 'seguridad',
    status: 'ready',
    ...PDF,
    multiple: false,
    minFiles: 1,
    options: [
      { key: 'applyTo', type: 'select', default: 'one', choices: ['one', 'all'] },
    ],
    load: () => import('./impl/sign').then((m) => m.run),
    Preview: SignaturePreview,
  },
  {
    slug: 'edit',
    icon: 'edit',
    category: 'edicion',
    status: 'ready',
    ...PDF,
    multiple: false,
    minFiles: 1,
    load: () => import('./impl/edit').then((m) => m.run),
    Preview: EditPreview,
  },
  {
    slug: 'redact',
    icon: 'eyeOff',
    category: 'seguridad',
    status: 'ready',
    ...PDF,
    multiple: false,
    minFiles: 1,
    load: () => import('./impl/redact').then((m) => m.run),
    Preview: RedactPreview,
  },
  {
    slug: 'metadata',
    icon: 'tag',
    category: 'conversiones',
    status: 'ready',
    ...PDF,
    multiple: false,
    minFiles: 1,
    workflow: true,
    options: [
      { key: 'title', type: 'text', default: '' },
      { key: 'author', type: 'text', default: '' },
      { key: 'subject', type: 'text', default: '' },
      { key: 'keywords', type: 'text', default: '' },
    ],
    load: () => import('./impl/metadata').then((m) => m.run),
    Preview: MetadataPreview,
  },
  {
    slug: 'report',
    icon: 'code',
    category: 'conversiones',
    status: 'ready',
    ...PDF,
    multiple: false,
    minFiles: 1,
    load: () => import('./impl/report').then((m) => m.run),
  },
]

export function getTool(slug: string | undefined): Tool | undefined {
  return TOOLS.find((tool) => tool.slug === slug)
}

/**
 * Ordena las herramientas por uso (desc) y, como desempate, por el nombre
 * local que devuelve `nameOf`. Las `planned` siempre van al final: no se
 * pueden ejecutar y no tiene sentido medirlas. Las nunca usadas (contador 0)
 * se agrupan al final en orden alfabético.
 */
export function sortTools(tools: Tool[], nameOf: (tool: Tool) => string): Tool[] {
  const usage = getToolUsage()
  return tools.slice().sort((a, b) => {
    if (a.status !== b.status) return a.status === 'ready' ? -1 : 1
    const countA = usage[a.slug] ?? 0
    const countB = usage[b.slug] ?? 0
    if (countA !== countB) return countB - countA
    return nameOf(a).localeCompare(nameOf(b))
  })
}
