import type { Tool, ToolCategoryId } from './types'
import { CropPreview } from './CropPreview'
import { OrganizePreview } from './OrganizePreview'
import { RedactPreview } from './RedactPreview'
import { SignaturePreview } from './SignaturePreview'

/** Los ids son estables: se usan como ancla en la URL y como clave del diccionario. */
export const CATEGORY_IDS: ToolCategoryId[] = [
  'paginas',
  'conversiones',
  'seguridad',
]

const PDF = { accept: 'application/pdf,.pdf', acceptKey: 'pdf' } as const

export const TOOLS: Tool[] = [
  {
    slug: 'merge',
    icon: 'merge',
    category: 'paginas',
    status: 'ready',
    ...PDF,
    multiple: true,
    minFiles: 2,
    load: () => import('./impl/merge').then((m) => m.run),
  },
  {
    slug: 'split',
    icon: 'split',
    category: 'paginas',
    status: 'ready',
    ...PDF,
    multiple: false,
    minFiles: 1,
    options: [
      { key: 'mode', type: 'select', default: 'ranges', choices: ['ranges', 'extract', 'each'] },
      {
        key: 'ranges',
        type: 'text',
        default: '1-',
        // Un ejemplo de rangos no se traduce.
        placeholder: '1-3, 5, 9-',
        showIf: (values) => values.mode !== 'each',
      },
    ],
    load: () => import('./impl/split').then((m) => m.run),
  },
  {
    slug: 'rotate',
    icon: 'rotate',
    category: 'paginas',
    status: 'ready',
    ...PDF,
    multiple: false,
    minFiles: 1,
    options: [
      { key: 'angle', type: 'select', default: '90', choices: ['90', '180', '270'] },
      { key: 'pages', type: 'text', default: '1-', placeholder: '1-3, 5' },
    ],
    load: () => import('./impl/rotate').then((m) => m.run),
  },
  {
    slug: 'organize',
    icon: 'grid',
    category: 'paginas',
    status: 'ready',
    ...PDF,
    multiple: false,
    minFiles: 1,
    load: () => import('./impl/organize').then((m) => m.run),
    Preview: OrganizePreview,
  },
  {
    slug: 'number',
    icon: 'hash',
    category: 'paginas',
    status: 'ready',
    ...PDF,
    multiple: false,
    minFiles: 1,
    options: [
      {
        key: 'position',
        type: 'select',
        default: 'bottom-center',
        choices: [
          'bottom-center',
          'bottom-right',
          'bottom-left',
          'top-center',
          'top-right',
          'top-left',
        ],
      },
      { key: 'start', type: 'number', default: 1, min: 0, max: 9999 },
      { key: 'size', type: 'number', default: 10, min: 6, max: 48 },
      { key: 'margin', type: 'number', default: 28, min: 4, max: 120, step: 4 },
      { key: 'withTotal', type: 'toggle', default: false },
      { key: 'skipFirst', type: 'toggle', default: false },
    ],
    load: () => import('./impl/number').then((m) => m.run),
  },
  {
    slug: 'watermark',
    icon: 'droplet',
    category: 'paginas',
    status: 'ready',
    ...PDF,
    multiple: false,
    minFiles: 1,
    options: [
      { key: 'text', type: 'text', default: 'CONFIDENCIAL' },
      {
        key: 'position',
        type: 'select',
        default: 'center',
        choices: [
          'center',
          'top-left',
          'top-center',
          'top-right',
          'bottom-left',
          'bottom-center',
          'bottom-right',
        ],
      },
      { key: 'color', type: 'select', default: 'gray', choices: ['gray', 'red', 'blue', 'black'] },
      { key: 'opacity', type: 'number', default: 20, min: 5, max: 100, step: 5 },
      { key: 'size', type: 'number', default: 72, min: 12, max: 200, step: 4 },
      { key: 'rotation', type: 'number', default: -45, min: -90, max: 90, step: 5 },
      { key: 'pages', type: 'text', default: '1-', placeholder: '1-3, 5' },
    ],
    load: () => import('./impl/watermark').then((m) => m.run),
  },
  {
    slug: 'crop',
    icon: 'crop',
    category: 'paginas',
    status: 'ready',
    ...PDF,
    multiple: false,
    minFiles: 1,
    options: [
      { key: 'applyTo', type: 'select', default: 'all', choices: ['all', 'one'] },
    ],
    load: () => import('./impl/crop').then((m) => m.run),
    Preview: CropPreview,
  },
  {
    slug: 'compare',
    icon: 'diff',
    category: 'paginas',
    status: 'ready',
    ...PDF,
    multiple: true,
    minFiles: 2,
    options: [
      { key: 'tolerance', type: 'number', default: 30, min: 0, max: 255 },
    ],
    load: () => import('./impl/compare').then((m) => m.run),
  },

  {
    slug: 'jpg-to-pdf',
    icon: 'image',
    category: 'conversiones',
    status: 'ready',
    accept: 'image/jpeg,image/png,.jpg,.jpeg,.png',
    acceptKey: 'image',
    multiple: true,
    minFiles: 1,
    options: [
      { key: 'pageSize', type: 'select', default: 'a4', choices: ['a4', 'letter', 'fit'] },
      {
        key: 'landscape',
        type: 'toggle',
        default: false,
        showIf: (values) => values.pageSize !== 'fit',
      },
      {
        key: 'margin',
        type: 'number',
        default: 24,
        min: 0,
        max: 200,
        step: 4,
        showIf: (values) => values.pageSize !== 'fit',
      },
    ],
    load: () => import('./impl/images-to-pdf').then((m) => m.run),
  },
  {
    slug: 'pdf-to-jpg',
    icon: 'file',
    category: 'conversiones',
    status: 'ready',
    ...PDF,
    multiple: false,
    minFiles: 1,
    options: [
      { key: 'pages', type: 'text', default: '1-', placeholder: '1-3, 5' },
      { key: 'format', type: 'select', default: 'jpeg', choices: ['jpeg', 'png'] },
      { key: 'scale', type: 'select', default: '2', choices: ['1', '2', '4'] },
      {
        key: 'quality',
        type: 'number',
        default: 85,
        min: 40,
        max: 100,
        step: 5,
        showIf: (values) => values.format === 'jpeg',
      },
    ],
    load: () => import('./impl/pdf-to-images').then((m) => m.run),
  },
  {
    slug: 'extract-images',
    icon: 'image',
    category: 'conversiones',
    status: 'ready',
    ...PDF,
    multiple: false,
    minFiles: 1,
    load: () => import('./impl/extract-images').then((m) => m.run),
  },
  {
    slug: 'pdf-to-text',
    icon: 'text',
    category: 'conversiones',
    status: 'ready',
    ...PDF,
    multiple: false,
    minFiles: 1,
    load: () => import('./impl/pdf-to-text').then((m) => m.run),
  },
  {
    slug: 'ocr',
    icon: 'scan',
    category: 'conversiones',
    status: 'ready',
    ...PDF,
    multiple: false,
    minFiles: 1,
    options: [
      { key: 'language', type: 'select', default: 'spa', choices: ['spa', 'eng'] },
    ],
    load: () => import('./impl/ocr').then((m) => m.run),
  },
  {
    slug: 'compress',
    icon: 'compress',
    category: 'conversiones',
    status: 'ready',
    ...PDF,
    multiple: false,
    minFiles: 1,
    options: [
      { key: 'level', type: 'select', default: 'balanced', choices: ['light', 'balanced', 'max'] },
    ],
    load: () => import('./impl/compress').then((m) => m.run),
  },
  {
    slug: 'repair',
    icon: 'wrench',
    category: 'conversiones',
    status: 'ready',
    ...PDF,
    multiple: false,
    minFiles: 1,
    load: () => import('./impl/repair').then((m) => m.run),
  },
  {
    slug: 'protect',
    icon: 'lock',
    category: 'seguridad',
    status: 'ready',
    ...PDF,
    multiple: false,
    minFiles: 1,
    options: [
      { key: 'password', type: 'password', default: '' },
      { key: 'confirm', type: 'password', default: '' },
    ],
    load: () => import('./impl/protect').then((m) => m.run),
  },
  {
    slug: 'unlock',
    icon: 'unlock',
    category: 'seguridad',
    status: 'ready',
    ...PDF,
    multiple: false,
    minFiles: 1,
    options: [{ key: 'password', type: 'password', default: '' }],
    load: () => import('./impl/unlock').then((m) => m.run),
  },
  {
    slug: 'sign',
    icon: 'pen',
    category: 'seguridad',
    status: 'ready',
    ...PDF,
    multiple: false,
    minFiles: 1,
    options: [
      { key: 'applyTo', type: 'select', default: 'one', choices: ['one', 'all'] },
    ],
    load: () => import('./impl/sign').then((m) => m.run),
    Preview: SignaturePreview,
  },
  {
    slug: 'redact',
    icon: 'eyeOff',
    category: 'seguridad',
    status: 'ready',
    ...PDF,
    multiple: false,
    minFiles: 1,
    load: () => import('./impl/redact').then((m) => m.run),
    Preview: RedactPreview,
  },
]

export function getTool(slug: string | undefined): Tool | undefined {
  return TOOLS.find((tool) => tool.slug === slug)
}
